dist: xenial
language: python

cache: pip
before_install:
  - pip install --upgrade pip
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls

jobs:
  include:
    - python: '2.7'
      env: TOXENV=py27-dj111
    - python: '3.5'
      env: TOXENV=py35-dj111
    - python: '3.6'
      env: TOXENV=py36-dj111
    - python: '3.6'
      env: TOXENV=py36-dj20
    - python: '3.6'
      env: TOXENV=py36-dj21
    - python: '3.7'
      env: TOXENV=py37-dj111
    - python: '3.7'
      env: TOXENV=py37-dj20
    - python: '3.7'
      env: TOXENV=py37-dj21

    - python: '3.6'
      env: TOXENV=lint

    - stage: release
      python: '3.6'
      if: tag IS present
      deploy:
        provider: pypi
        user: Praekelt
        password:
          secure: C7lPYnZXMsg2FWAe3SD2OiD60GsrDvYgZeWtUBo1p/L68S4T5gaJB9AQXhC7MMR2I+C50ZSfAic/M4qSwYwv0i2bg0bwksTrCzweQQaCbggOVTtXQIIJ3FdP6FlNxM30cfTLpQmFiURdFIZitSgAONn4m7g8u6vaExNrW9bYxY0=
        distributions: sdist bdist_wheel
        on: {tags: true}

      install: skip
      script: skip
